apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: valaxy-devops-project
spec:
  selector:
    app: valaxy-devops-project
  type: LoadBalancer
  ports:
    - port: 8080      # loadbalancer port
      targetPort: 8080    # node port or the connection to a new service using its listening port
      nodePort: 31200 #node port
